-   id: clear-output
    name: clear jupyter notebook output
    description: Removes outputs from Jupyter notebooks.
    entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
    language: python
    types: [jupyter]
    stages: [pre-commit]
